"""fix email

Revision ID: 8eab511f3c65
Revises: 971672a77a13
Create Date: 2022-01-05 19:47:39.795801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eab511f3c65'
down_revision = '971672a77a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
